// Code generated by go-swagger; DO NOT EDIT.

package analytics_endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/go-opensea/opensea/models"
)

// GetCollectionStatsReader is a Reader for the GetCollectionStats structure.
type GetCollectionStatsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCollectionStatsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCollectionStatsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCollectionStatsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCollectionStatsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCollectionStatsOK creates a GetCollectionStatsOK with default headers values
func NewGetCollectionStatsOK() *GetCollectionStatsOK {
	return &GetCollectionStatsOK{}
}

/*
GetCollectionStatsOK describes a response with status code 200, with default header values.

GetCollectionStatsOK get collection stats o k
*/
type GetCollectionStatsOK struct {
	Payload *models.GetCollectionStatsResponse
}

// IsSuccess returns true when this get collection stats o k response has a 2xx status code
func (o *GetCollectionStatsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get collection stats o k response has a 3xx status code
func (o *GetCollectionStatsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get collection stats o k response has a 4xx status code
func (o *GetCollectionStatsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get collection stats o k response has a 5xx status code
func (o *GetCollectionStatsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get collection stats o k response a status code equal to that given
func (o *GetCollectionStatsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get collection stats o k response
func (o *GetCollectionStatsOK) Code() int {
	return 200
}

func (o *GetCollectionStatsOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/collections/{collection_slug}/stats][%d] getCollectionStatsOK  %+v", 200, o.Payload)
}

func (o *GetCollectionStatsOK) String() string {
	return fmt.Sprintf("[GET /api/v2/collections/{collection_slug}/stats][%d] getCollectionStatsOK  %+v", 200, o.Payload)
}

func (o *GetCollectionStatsOK) GetPayload() *models.GetCollectionStatsResponse {
	return o.Payload
}

func (o *GetCollectionStatsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetCollectionStatsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCollectionStatsBadRequest creates a GetCollectionStatsBadRequest with default headers values
func NewGetCollectionStatsBadRequest() *GetCollectionStatsBadRequest {
	return &GetCollectionStatsBadRequest{}
}

/*
GetCollectionStatsBadRequest describes a response with status code 400, with default header values.

For error reasons, review the response data.
*/
type GetCollectionStatsBadRequest struct {
}

// IsSuccess returns true when this get collection stats bad request response has a 2xx status code
func (o *GetCollectionStatsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get collection stats bad request response has a 3xx status code
func (o *GetCollectionStatsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get collection stats bad request response has a 4xx status code
func (o *GetCollectionStatsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get collection stats bad request response has a 5xx status code
func (o *GetCollectionStatsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get collection stats bad request response a status code equal to that given
func (o *GetCollectionStatsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get collection stats bad request response
func (o *GetCollectionStatsBadRequest) Code() int {
	return 400
}

func (o *GetCollectionStatsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/collections/{collection_slug}/stats][%d] getCollectionStatsBadRequest ", 400)
}

func (o *GetCollectionStatsBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v2/collections/{collection_slug}/stats][%d] getCollectionStatsBadRequest ", 400)
}

func (o *GetCollectionStatsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetCollectionStatsInternalServerError creates a GetCollectionStatsInternalServerError with default headers values
func NewGetCollectionStatsInternalServerError() *GetCollectionStatsInternalServerError {
	return &GetCollectionStatsInternalServerError{}
}

/*
GetCollectionStatsInternalServerError describes a response with status code 500, with default header values.

Internal server error. Please open a support ticket so OpenSea can investigate.
*/
type GetCollectionStatsInternalServerError struct {
}

// IsSuccess returns true when this get collection stats internal server error response has a 2xx status code
func (o *GetCollectionStatsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get collection stats internal server error response has a 3xx status code
func (o *GetCollectionStatsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get collection stats internal server error response has a 4xx status code
func (o *GetCollectionStatsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get collection stats internal server error response has a 5xx status code
func (o *GetCollectionStatsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get collection stats internal server error response a status code equal to that given
func (o *GetCollectionStatsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get collection stats internal server error response
func (o *GetCollectionStatsInternalServerError) Code() int {
	return 500
}

func (o *GetCollectionStatsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v2/collections/{collection_slug}/stats][%d] getCollectionStatsInternalServerError ", 500)
}

func (o *GetCollectionStatsInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v2/collections/{collection_slug}/stats][%d] getCollectionStatsInternalServerError ", 500)
}

func (o *GetCollectionStatsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
