// Code generated by go-swagger; DO NOT EDIT.

package transaction_endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/go-opensea/opensea/models"
)

// BuildOfferV2Reader is a Reader for the BuildOfferV2 structure.
type BuildOfferV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BuildOfferV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBuildOfferV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewBuildOfferV2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewBuildOfferV2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewBuildOfferV2OK creates a BuildOfferV2OK with default headers values
func NewBuildOfferV2OK() *BuildOfferV2OK {
	return &BuildOfferV2OK{}
}

/*
BuildOfferV2OK describes a response with status code 200, with default header values.

BuildOfferV2OK build offer v2 o k
*/
type BuildOfferV2OK struct {
	Payload *models.BuildOffer
}

// IsSuccess returns true when this build offer v2 o k response has a 2xx status code
func (o *BuildOfferV2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this build offer v2 o k response has a 3xx status code
func (o *BuildOfferV2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this build offer v2 o k response has a 4xx status code
func (o *BuildOfferV2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this build offer v2 o k response has a 5xx status code
func (o *BuildOfferV2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this build offer v2 o k response a status code equal to that given
func (o *BuildOfferV2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the build offer v2 o k response
func (o *BuildOfferV2OK) Code() int {
	return 200
}

func (o *BuildOfferV2OK) Error() string {
	return fmt.Sprintf("[POST /api/v2/offers/build][%d] buildOfferV2OK  %+v", 200, o.Payload)
}

func (o *BuildOfferV2OK) String() string {
	return fmt.Sprintf("[POST /api/v2/offers/build][%d] buildOfferV2OK  %+v", 200, o.Payload)
}

func (o *BuildOfferV2OK) GetPayload() *models.BuildOffer {
	return o.Payload
}

func (o *BuildOfferV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BuildOffer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBuildOfferV2BadRequest creates a BuildOfferV2BadRequest with default headers values
func NewBuildOfferV2BadRequest() *BuildOfferV2BadRequest {
	return &BuildOfferV2BadRequest{}
}

/*
BuildOfferV2BadRequest describes a response with status code 400, with default header values.

For error reasons, review the response data.
*/
type BuildOfferV2BadRequest struct {
}

// IsSuccess returns true when this build offer v2 bad request response has a 2xx status code
func (o *BuildOfferV2BadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this build offer v2 bad request response has a 3xx status code
func (o *BuildOfferV2BadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this build offer v2 bad request response has a 4xx status code
func (o *BuildOfferV2BadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this build offer v2 bad request response has a 5xx status code
func (o *BuildOfferV2BadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this build offer v2 bad request response a status code equal to that given
func (o *BuildOfferV2BadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the build offer v2 bad request response
func (o *BuildOfferV2BadRequest) Code() int {
	return 400
}

func (o *BuildOfferV2BadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/offers/build][%d] buildOfferV2BadRequest ", 400)
}

func (o *BuildOfferV2BadRequest) String() string {
	return fmt.Sprintf("[POST /api/v2/offers/build][%d] buildOfferV2BadRequest ", 400)
}

func (o *BuildOfferV2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewBuildOfferV2InternalServerError creates a BuildOfferV2InternalServerError with default headers values
func NewBuildOfferV2InternalServerError() *BuildOfferV2InternalServerError {
	return &BuildOfferV2InternalServerError{}
}

/*
BuildOfferV2InternalServerError describes a response with status code 500, with default header values.

Internal server error. Please open a support ticket so OpenSea can investigate.
*/
type BuildOfferV2InternalServerError struct {
}

// IsSuccess returns true when this build offer v2 internal server error response has a 2xx status code
func (o *BuildOfferV2InternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this build offer v2 internal server error response has a 3xx status code
func (o *BuildOfferV2InternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this build offer v2 internal server error response has a 4xx status code
func (o *BuildOfferV2InternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this build offer v2 internal server error response has a 5xx status code
func (o *BuildOfferV2InternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this build offer v2 internal server error response a status code equal to that given
func (o *BuildOfferV2InternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the build offer v2 internal server error response
func (o *BuildOfferV2InternalServerError) Code() int {
	return 500
}

func (o *BuildOfferV2InternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v2/offers/build][%d] buildOfferV2InternalServerError ", 500)
}

func (o *BuildOfferV2InternalServerError) String() string {
	return fmt.Sprintf("[POST /api/v2/offers/build][%d] buildOfferV2InternalServerError ", 500)
}

func (o *BuildOfferV2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
