// Code generated by go-swagger; DO NOT EDIT.

package transaction_endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/go-opensea/opensea/models"
)

// GenerateOfferFulfillmentDataV2Reader is a Reader for the GenerateOfferFulfillmentDataV2 structure.
type GenerateOfferFulfillmentDataV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GenerateOfferFulfillmentDataV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGenerateOfferFulfillmentDataV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGenerateOfferFulfillmentDataV2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGenerateOfferFulfillmentDataV2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGenerateOfferFulfillmentDataV2OK creates a GenerateOfferFulfillmentDataV2OK with default headers values
func NewGenerateOfferFulfillmentDataV2OK() *GenerateOfferFulfillmentDataV2OK {
	return &GenerateOfferFulfillmentDataV2OK{}
}

/*
GenerateOfferFulfillmentDataV2OK describes a response with status code 200, with default header values.

GenerateOfferFulfillmentDataV2OK generate offer fulfillment data v2 o k
*/
type GenerateOfferFulfillmentDataV2OK struct {
	Payload *models.FulfillmentOutput
}

// IsSuccess returns true when this generate offer fulfillment data v2 o k response has a 2xx status code
func (o *GenerateOfferFulfillmentDataV2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this generate offer fulfillment data v2 o k response has a 3xx status code
func (o *GenerateOfferFulfillmentDataV2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this generate offer fulfillment data v2 o k response has a 4xx status code
func (o *GenerateOfferFulfillmentDataV2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this generate offer fulfillment data v2 o k response has a 5xx status code
func (o *GenerateOfferFulfillmentDataV2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this generate offer fulfillment data v2 o k response a status code equal to that given
func (o *GenerateOfferFulfillmentDataV2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the generate offer fulfillment data v2 o k response
func (o *GenerateOfferFulfillmentDataV2OK) Code() int {
	return 200
}

func (o *GenerateOfferFulfillmentDataV2OK) Error() string {
	return fmt.Sprintf("[POST /api/v2/offers/fulfillment_data][%d] generateOfferFulfillmentDataV2OK  %+v", 200, o.Payload)
}

func (o *GenerateOfferFulfillmentDataV2OK) String() string {
	return fmt.Sprintf("[POST /api/v2/offers/fulfillment_data][%d] generateOfferFulfillmentDataV2OK  %+v", 200, o.Payload)
}

func (o *GenerateOfferFulfillmentDataV2OK) GetPayload() *models.FulfillmentOutput {
	return o.Payload
}

func (o *GenerateOfferFulfillmentDataV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FulfillmentOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGenerateOfferFulfillmentDataV2BadRequest creates a GenerateOfferFulfillmentDataV2BadRequest with default headers values
func NewGenerateOfferFulfillmentDataV2BadRequest() *GenerateOfferFulfillmentDataV2BadRequest {
	return &GenerateOfferFulfillmentDataV2BadRequest{}
}

/*
	GenerateOfferFulfillmentDataV2BadRequest describes a response with status code 400, with default header values.

	The request is invalid

The order_hash does not exist
The chain is not an EVM Chain
The protocol_address is not a supported Seaport contract
For other error reasons, see the response data.
*/
type GenerateOfferFulfillmentDataV2BadRequest struct {
}

// IsSuccess returns true when this generate offer fulfillment data v2 bad request response has a 2xx status code
func (o *GenerateOfferFulfillmentDataV2BadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this generate offer fulfillment data v2 bad request response has a 3xx status code
func (o *GenerateOfferFulfillmentDataV2BadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this generate offer fulfillment data v2 bad request response has a 4xx status code
func (o *GenerateOfferFulfillmentDataV2BadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this generate offer fulfillment data v2 bad request response has a 5xx status code
func (o *GenerateOfferFulfillmentDataV2BadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this generate offer fulfillment data v2 bad request response a status code equal to that given
func (o *GenerateOfferFulfillmentDataV2BadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the generate offer fulfillment data v2 bad request response
func (o *GenerateOfferFulfillmentDataV2BadRequest) Code() int {
	return 400
}

func (o *GenerateOfferFulfillmentDataV2BadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/offers/fulfillment_data][%d] generateOfferFulfillmentDataV2BadRequest ", 400)
}

func (o *GenerateOfferFulfillmentDataV2BadRequest) String() string {
	return fmt.Sprintf("[POST /api/v2/offers/fulfillment_data][%d] generateOfferFulfillmentDataV2BadRequest ", 400)
}

func (o *GenerateOfferFulfillmentDataV2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGenerateOfferFulfillmentDataV2InternalServerError creates a GenerateOfferFulfillmentDataV2InternalServerError with default headers values
func NewGenerateOfferFulfillmentDataV2InternalServerError() *GenerateOfferFulfillmentDataV2InternalServerError {
	return &GenerateOfferFulfillmentDataV2InternalServerError{}
}

/*
GenerateOfferFulfillmentDataV2InternalServerError describes a response with status code 500, with default header values.

Internal server error. Please open a support ticket so OpenSea can investigate.
*/
type GenerateOfferFulfillmentDataV2InternalServerError struct {
}

// IsSuccess returns true when this generate offer fulfillment data v2 internal server error response has a 2xx status code
func (o *GenerateOfferFulfillmentDataV2InternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this generate offer fulfillment data v2 internal server error response has a 3xx status code
func (o *GenerateOfferFulfillmentDataV2InternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this generate offer fulfillment data v2 internal server error response has a 4xx status code
func (o *GenerateOfferFulfillmentDataV2InternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this generate offer fulfillment data v2 internal server error response has a 5xx status code
func (o *GenerateOfferFulfillmentDataV2InternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this generate offer fulfillment data v2 internal server error response a status code equal to that given
func (o *GenerateOfferFulfillmentDataV2InternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the generate offer fulfillment data v2 internal server error response
func (o *GenerateOfferFulfillmentDataV2InternalServerError) Code() int {
	return 500
}

func (o *GenerateOfferFulfillmentDataV2InternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v2/offers/fulfillment_data][%d] generateOfferFulfillmentDataV2InternalServerError ", 500)
}

func (o *GenerateOfferFulfillmentDataV2InternalServerError) String() string {
	return fmt.Sprintf("[POST /api/v2/offers/fulfillment_data][%d] generateOfferFulfillmentDataV2InternalServerError ", 500)
}

func (o *GenerateOfferFulfillmentDataV2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
