// Code generated by go-swagger; DO NOT EDIT.

package transaction_endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/go-opensea/opensea/models"
)

// NewGenerateOfferFulfillmentDataV2Params creates a new GenerateOfferFulfillmentDataV2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGenerateOfferFulfillmentDataV2Params() *GenerateOfferFulfillmentDataV2Params {
	return &GenerateOfferFulfillmentDataV2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewGenerateOfferFulfillmentDataV2ParamsWithTimeout creates a new GenerateOfferFulfillmentDataV2Params object
// with the ability to set a timeout on a request.
func NewGenerateOfferFulfillmentDataV2ParamsWithTimeout(timeout time.Duration) *GenerateOfferFulfillmentDataV2Params {
	return &GenerateOfferFulfillmentDataV2Params{
		timeout: timeout,
	}
}

// NewGenerateOfferFulfillmentDataV2ParamsWithContext creates a new GenerateOfferFulfillmentDataV2Params object
// with the ability to set a context for a request.
func NewGenerateOfferFulfillmentDataV2ParamsWithContext(ctx context.Context) *GenerateOfferFulfillmentDataV2Params {
	return &GenerateOfferFulfillmentDataV2Params{
		Context: ctx,
	}
}

// NewGenerateOfferFulfillmentDataV2ParamsWithHTTPClient creates a new GenerateOfferFulfillmentDataV2Params object
// with the ability to set a custom HTTPClient for a request.
func NewGenerateOfferFulfillmentDataV2ParamsWithHTTPClient(client *http.Client) *GenerateOfferFulfillmentDataV2Params {
	return &GenerateOfferFulfillmentDataV2Params{
		HTTPClient: client,
	}
}

/*
GenerateOfferFulfillmentDataV2Params contains all the parameters to send to the API endpoint

	for the generate offer fulfillment data v2 operation.

	Typically these are written to a http.Request.
*/
type GenerateOfferFulfillmentDataV2Params struct {

	// Body.
	Body *models.GenerateOfferFulfillmentInput

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the generate offer fulfillment data v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateOfferFulfillmentDataV2Params) WithDefaults() *GenerateOfferFulfillmentDataV2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the generate offer fulfillment data v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateOfferFulfillmentDataV2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the generate offer fulfillment data v2 params
func (o *GenerateOfferFulfillmentDataV2Params) WithTimeout(timeout time.Duration) *GenerateOfferFulfillmentDataV2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the generate offer fulfillment data v2 params
func (o *GenerateOfferFulfillmentDataV2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the generate offer fulfillment data v2 params
func (o *GenerateOfferFulfillmentDataV2Params) WithContext(ctx context.Context) *GenerateOfferFulfillmentDataV2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the generate offer fulfillment data v2 params
func (o *GenerateOfferFulfillmentDataV2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the generate offer fulfillment data v2 params
func (o *GenerateOfferFulfillmentDataV2Params) WithHTTPClient(client *http.Client) *GenerateOfferFulfillmentDataV2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the generate offer fulfillment data v2 params
func (o *GenerateOfferFulfillmentDataV2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the generate offer fulfillment data v2 params
func (o *GenerateOfferFulfillmentDataV2Params) WithBody(body *models.GenerateOfferFulfillmentInput) *GenerateOfferFulfillmentDataV2Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the generate offer fulfillment data v2 params
func (o *GenerateOfferFulfillmentDataV2Params) SetBody(body *models.GenerateOfferFulfillmentInput) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GenerateOfferFulfillmentDataV2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
