// Code generated by go-swagger; DO NOT EDIT.

package transaction_endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/go-opensea/opensea/models"
)

// GetAllListingsOnCollectionV2Reader is a Reader for the GetAllListingsOnCollectionV2 structure.
type GetAllListingsOnCollectionV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllListingsOnCollectionV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllListingsOnCollectionV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAllListingsOnCollectionV2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAllListingsOnCollectionV2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllListingsOnCollectionV2OK creates a GetAllListingsOnCollectionV2OK with default headers values
func NewGetAllListingsOnCollectionV2OK() *GetAllListingsOnCollectionV2OK {
	return &GetAllListingsOnCollectionV2OK{}
}

/*
GetAllListingsOnCollectionV2OK describes a response with status code 200, with default header values.

GetAllListingsOnCollectionV2OK get all listings on collection v2 o k
*/
type GetAllListingsOnCollectionV2OK struct {
	Payload *models.PaginatedListingList
}

// IsSuccess returns true when this get all listings on collection v2 o k response has a 2xx status code
func (o *GetAllListingsOnCollectionV2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get all listings on collection v2 o k response has a 3xx status code
func (o *GetAllListingsOnCollectionV2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all listings on collection v2 o k response has a 4xx status code
func (o *GetAllListingsOnCollectionV2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get all listings on collection v2 o k response has a 5xx status code
func (o *GetAllListingsOnCollectionV2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this get all listings on collection v2 o k response a status code equal to that given
func (o *GetAllListingsOnCollectionV2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get all listings on collection v2 o k response
func (o *GetAllListingsOnCollectionV2OK) Code() int {
	return 200
}

func (o *GetAllListingsOnCollectionV2OK) Error() string {
	return fmt.Sprintf("[GET /api/v2/listings/collection/{collection_slug}/all][%d] getAllListingsOnCollectionV2OK  %+v", 200, o.Payload)
}

func (o *GetAllListingsOnCollectionV2OK) String() string {
	return fmt.Sprintf("[GET /api/v2/listings/collection/{collection_slug}/all][%d] getAllListingsOnCollectionV2OK  %+v", 200, o.Payload)
}

func (o *GetAllListingsOnCollectionV2OK) GetPayload() *models.PaginatedListingList {
	return o.Payload
}

func (o *GetAllListingsOnCollectionV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaginatedListingList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllListingsOnCollectionV2BadRequest creates a GetAllListingsOnCollectionV2BadRequest with default headers values
func NewGetAllListingsOnCollectionV2BadRequest() *GetAllListingsOnCollectionV2BadRequest {
	return &GetAllListingsOnCollectionV2BadRequest{}
}

/*
	GetAllListingsOnCollectionV2BadRequest describes a response with status code 400, with default header values.

	The collection requested does not exist.

The query parameters can not be parsed.
*/
type GetAllListingsOnCollectionV2BadRequest struct {
}

// IsSuccess returns true when this get all listings on collection v2 bad request response has a 2xx status code
func (o *GetAllListingsOnCollectionV2BadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get all listings on collection v2 bad request response has a 3xx status code
func (o *GetAllListingsOnCollectionV2BadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all listings on collection v2 bad request response has a 4xx status code
func (o *GetAllListingsOnCollectionV2BadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get all listings on collection v2 bad request response has a 5xx status code
func (o *GetAllListingsOnCollectionV2BadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get all listings on collection v2 bad request response a status code equal to that given
func (o *GetAllListingsOnCollectionV2BadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get all listings on collection v2 bad request response
func (o *GetAllListingsOnCollectionV2BadRequest) Code() int {
	return 400
}

func (o *GetAllListingsOnCollectionV2BadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/listings/collection/{collection_slug}/all][%d] getAllListingsOnCollectionV2BadRequest ", 400)
}

func (o *GetAllListingsOnCollectionV2BadRequest) String() string {
	return fmt.Sprintf("[GET /api/v2/listings/collection/{collection_slug}/all][%d] getAllListingsOnCollectionV2BadRequest ", 400)
}

func (o *GetAllListingsOnCollectionV2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllListingsOnCollectionV2InternalServerError creates a GetAllListingsOnCollectionV2InternalServerError with default headers values
func NewGetAllListingsOnCollectionV2InternalServerError() *GetAllListingsOnCollectionV2InternalServerError {
	return &GetAllListingsOnCollectionV2InternalServerError{}
}

/*
GetAllListingsOnCollectionV2InternalServerError describes a response with status code 500, with default header values.

Internal server error. Please open a support ticket so OpenSea can investigate.
*/
type GetAllListingsOnCollectionV2InternalServerError struct {
}

// IsSuccess returns true when this get all listings on collection v2 internal server error response has a 2xx status code
func (o *GetAllListingsOnCollectionV2InternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get all listings on collection v2 internal server error response has a 3xx status code
func (o *GetAllListingsOnCollectionV2InternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all listings on collection v2 internal server error response has a 4xx status code
func (o *GetAllListingsOnCollectionV2InternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get all listings on collection v2 internal server error response has a 5xx status code
func (o *GetAllListingsOnCollectionV2InternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get all listings on collection v2 internal server error response a status code equal to that given
func (o *GetAllListingsOnCollectionV2InternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get all listings on collection v2 internal server error response
func (o *GetAllListingsOnCollectionV2InternalServerError) Code() int {
	return 500
}

func (o *GetAllListingsOnCollectionV2InternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v2/listings/collection/{collection_slug}/all][%d] getAllListingsOnCollectionV2InternalServerError ", 500)
}

func (o *GetAllListingsOnCollectionV2InternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v2/listings/collection/{collection_slug}/all][%d] getAllListingsOnCollectionV2InternalServerError ", 500)
}

func (o *GetAllListingsOnCollectionV2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
