// Code generated by go-swagger; DO NOT EDIT.

package transaction_endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/go-opensea/opensea/models"
)

// GetAllOffersOnCollectionV2Reader is a Reader for the GetAllOffersOnCollectionV2 structure.
type GetAllOffersOnCollectionV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllOffersOnCollectionV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllOffersOnCollectionV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAllOffersOnCollectionV2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAllOffersOnCollectionV2NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAllOffersOnCollectionV2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllOffersOnCollectionV2OK creates a GetAllOffersOnCollectionV2OK with default headers values
func NewGetAllOffersOnCollectionV2OK() *GetAllOffersOnCollectionV2OK {
	return &GetAllOffersOnCollectionV2OK{}
}

/*
GetAllOffersOnCollectionV2OK describes a response with status code 200, with default header values.

GetAllOffersOnCollectionV2OK get all offers on collection v2 o k
*/
type GetAllOffersOnCollectionV2OK struct {
	Payload *models.PaginatedOfferList
}

// IsSuccess returns true when this get all offers on collection v2 o k response has a 2xx status code
func (o *GetAllOffersOnCollectionV2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get all offers on collection v2 o k response has a 3xx status code
func (o *GetAllOffersOnCollectionV2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all offers on collection v2 o k response has a 4xx status code
func (o *GetAllOffersOnCollectionV2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get all offers on collection v2 o k response has a 5xx status code
func (o *GetAllOffersOnCollectionV2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this get all offers on collection v2 o k response a status code equal to that given
func (o *GetAllOffersOnCollectionV2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get all offers on collection v2 o k response
func (o *GetAllOffersOnCollectionV2OK) Code() int {
	return 200
}

func (o *GetAllOffersOnCollectionV2OK) Error() string {
	return fmt.Sprintf("[GET /api/v2/offers/collection/{collection_slug}/all][%d] getAllOffersOnCollectionV2OK  %+v", 200, o.Payload)
}

func (o *GetAllOffersOnCollectionV2OK) String() string {
	return fmt.Sprintf("[GET /api/v2/offers/collection/{collection_slug}/all][%d] getAllOffersOnCollectionV2OK  %+v", 200, o.Payload)
}

func (o *GetAllOffersOnCollectionV2OK) GetPayload() *models.PaginatedOfferList {
	return o.Payload
}

func (o *GetAllOffersOnCollectionV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaginatedOfferList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllOffersOnCollectionV2BadRequest creates a GetAllOffersOnCollectionV2BadRequest with default headers values
func NewGetAllOffersOnCollectionV2BadRequest() *GetAllOffersOnCollectionV2BadRequest {
	return &GetAllOffersOnCollectionV2BadRequest{}
}

/*
GetAllOffersOnCollectionV2BadRequest describes a response with status code 400, with default header values.

For error reasons, review the response data.
*/
type GetAllOffersOnCollectionV2BadRequest struct {
}

// IsSuccess returns true when this get all offers on collection v2 bad request response has a 2xx status code
func (o *GetAllOffersOnCollectionV2BadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get all offers on collection v2 bad request response has a 3xx status code
func (o *GetAllOffersOnCollectionV2BadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all offers on collection v2 bad request response has a 4xx status code
func (o *GetAllOffersOnCollectionV2BadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get all offers on collection v2 bad request response has a 5xx status code
func (o *GetAllOffersOnCollectionV2BadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get all offers on collection v2 bad request response a status code equal to that given
func (o *GetAllOffersOnCollectionV2BadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get all offers on collection v2 bad request response
func (o *GetAllOffersOnCollectionV2BadRequest) Code() int {
	return 400
}

func (o *GetAllOffersOnCollectionV2BadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/offers/collection/{collection_slug}/all][%d] getAllOffersOnCollectionV2BadRequest ", 400)
}

func (o *GetAllOffersOnCollectionV2BadRequest) String() string {
	return fmt.Sprintf("[GET /api/v2/offers/collection/{collection_slug}/all][%d] getAllOffersOnCollectionV2BadRequest ", 400)
}

func (o *GetAllOffersOnCollectionV2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllOffersOnCollectionV2NotFound creates a GetAllOffersOnCollectionV2NotFound with default headers values
func NewGetAllOffersOnCollectionV2NotFound() *GetAllOffersOnCollectionV2NotFound {
	return &GetAllOffersOnCollectionV2NotFound{}
}

/*
GetAllOffersOnCollectionV2NotFound describes a response with status code 404, with default header values.

Returned when the collection does not exist.
*/
type GetAllOffersOnCollectionV2NotFound struct {
}

// IsSuccess returns true when this get all offers on collection v2 not found response has a 2xx status code
func (o *GetAllOffersOnCollectionV2NotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get all offers on collection v2 not found response has a 3xx status code
func (o *GetAllOffersOnCollectionV2NotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all offers on collection v2 not found response has a 4xx status code
func (o *GetAllOffersOnCollectionV2NotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get all offers on collection v2 not found response has a 5xx status code
func (o *GetAllOffersOnCollectionV2NotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get all offers on collection v2 not found response a status code equal to that given
func (o *GetAllOffersOnCollectionV2NotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get all offers on collection v2 not found response
func (o *GetAllOffersOnCollectionV2NotFound) Code() int {
	return 404
}

func (o *GetAllOffersOnCollectionV2NotFound) Error() string {
	return fmt.Sprintf("[GET /api/v2/offers/collection/{collection_slug}/all][%d] getAllOffersOnCollectionV2NotFound ", 404)
}

func (o *GetAllOffersOnCollectionV2NotFound) String() string {
	return fmt.Sprintf("[GET /api/v2/offers/collection/{collection_slug}/all][%d] getAllOffersOnCollectionV2NotFound ", 404)
}

func (o *GetAllOffersOnCollectionV2NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllOffersOnCollectionV2InternalServerError creates a GetAllOffersOnCollectionV2InternalServerError with default headers values
func NewGetAllOffersOnCollectionV2InternalServerError() *GetAllOffersOnCollectionV2InternalServerError {
	return &GetAllOffersOnCollectionV2InternalServerError{}
}

/*
GetAllOffersOnCollectionV2InternalServerError describes a response with status code 500, with default header values.

Internal server error. Please open a support ticket so OpenSea can investigate.
*/
type GetAllOffersOnCollectionV2InternalServerError struct {
}

// IsSuccess returns true when this get all offers on collection v2 internal server error response has a 2xx status code
func (o *GetAllOffersOnCollectionV2InternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get all offers on collection v2 internal server error response has a 3xx status code
func (o *GetAllOffersOnCollectionV2InternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all offers on collection v2 internal server error response has a 4xx status code
func (o *GetAllOffersOnCollectionV2InternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get all offers on collection v2 internal server error response has a 5xx status code
func (o *GetAllOffersOnCollectionV2InternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get all offers on collection v2 internal server error response a status code equal to that given
func (o *GetAllOffersOnCollectionV2InternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get all offers on collection v2 internal server error response
func (o *GetAllOffersOnCollectionV2InternalServerError) Code() int {
	return 500
}

func (o *GetAllOffersOnCollectionV2InternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v2/offers/collection/{collection_slug}/all][%d] getAllOffersOnCollectionV2InternalServerError ", 500)
}

func (o *GetAllOffersOnCollectionV2InternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v2/offers/collection/{collection_slug}/all][%d] getAllOffersOnCollectionV2InternalServerError ", 500)
}

func (o *GetAllOffersOnCollectionV2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
