// Code generated by go-swagger; DO NOT EDIT.

package transaction_endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/go-opensea/opensea/models"
)

// GetTraitOffersV2Reader is a Reader for the GetTraitOffersV2 structure.
type GetTraitOffersV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTraitOffersV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTraitOffersV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetTraitOffersV2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetTraitOffersV2NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetTraitOffersV2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTraitOffersV2OK creates a GetTraitOffersV2OK with default headers values
func NewGetTraitOffersV2OK() *GetTraitOffersV2OK {
	return &GetTraitOffersV2OK{}
}

/*
GetTraitOffersV2OK describes a response with status code 200, with default header values.

GetTraitOffersV2OK get trait offers v2 o k
*/
type GetTraitOffersV2OK struct {
	Payload *models.OfferList
}

// IsSuccess returns true when this get trait offers v2 o k response has a 2xx status code
func (o *GetTraitOffersV2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get trait offers v2 o k response has a 3xx status code
func (o *GetTraitOffersV2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get trait offers v2 o k response has a 4xx status code
func (o *GetTraitOffersV2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get trait offers v2 o k response has a 5xx status code
func (o *GetTraitOffersV2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this get trait offers v2 o k response a status code equal to that given
func (o *GetTraitOffersV2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get trait offers v2 o k response
func (o *GetTraitOffersV2OK) Code() int {
	return 200
}

func (o *GetTraitOffersV2OK) Error() string {
	return fmt.Sprintf("[GET /api/v2/offers/collection/{collection_slug}/traits][%d] getTraitOffersV2OK  %+v", 200, o.Payload)
}

func (o *GetTraitOffersV2OK) String() string {
	return fmt.Sprintf("[GET /api/v2/offers/collection/{collection_slug}/traits][%d] getTraitOffersV2OK  %+v", 200, o.Payload)
}

func (o *GetTraitOffersV2OK) GetPayload() *models.OfferList {
	return o.Payload
}

func (o *GetTraitOffersV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OfferList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTraitOffersV2BadRequest creates a GetTraitOffersV2BadRequest with default headers values
func NewGetTraitOffersV2BadRequest() *GetTraitOffersV2BadRequest {
	return &GetTraitOffersV2BadRequest{}
}

/*
GetTraitOffersV2BadRequest describes a response with status code 400, with default header values.

For error reasons, review the response data.
*/
type GetTraitOffersV2BadRequest struct {
}

// IsSuccess returns true when this get trait offers v2 bad request response has a 2xx status code
func (o *GetTraitOffersV2BadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get trait offers v2 bad request response has a 3xx status code
func (o *GetTraitOffersV2BadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get trait offers v2 bad request response has a 4xx status code
func (o *GetTraitOffersV2BadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get trait offers v2 bad request response has a 5xx status code
func (o *GetTraitOffersV2BadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get trait offers v2 bad request response a status code equal to that given
func (o *GetTraitOffersV2BadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get trait offers v2 bad request response
func (o *GetTraitOffersV2BadRequest) Code() int {
	return 400
}

func (o *GetTraitOffersV2BadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/offers/collection/{collection_slug}/traits][%d] getTraitOffersV2BadRequest ", 400)
}

func (o *GetTraitOffersV2BadRequest) String() string {
	return fmt.Sprintf("[GET /api/v2/offers/collection/{collection_slug}/traits][%d] getTraitOffersV2BadRequest ", 400)
}

func (o *GetTraitOffersV2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTraitOffersV2NotFound creates a GetTraitOffersV2NotFound with default headers values
func NewGetTraitOffersV2NotFound() *GetTraitOffersV2NotFound {
	return &GetTraitOffersV2NotFound{}
}

/*
GetTraitOffersV2NotFound describes a response with status code 404, with default header values.

Returned when the collection does not exist.
*/
type GetTraitOffersV2NotFound struct {
}

// IsSuccess returns true when this get trait offers v2 not found response has a 2xx status code
func (o *GetTraitOffersV2NotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get trait offers v2 not found response has a 3xx status code
func (o *GetTraitOffersV2NotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get trait offers v2 not found response has a 4xx status code
func (o *GetTraitOffersV2NotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get trait offers v2 not found response has a 5xx status code
func (o *GetTraitOffersV2NotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get trait offers v2 not found response a status code equal to that given
func (o *GetTraitOffersV2NotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get trait offers v2 not found response
func (o *GetTraitOffersV2NotFound) Code() int {
	return 404
}

func (o *GetTraitOffersV2NotFound) Error() string {
	return fmt.Sprintf("[GET /api/v2/offers/collection/{collection_slug}/traits][%d] getTraitOffersV2NotFound ", 404)
}

func (o *GetTraitOffersV2NotFound) String() string {
	return fmt.Sprintf("[GET /api/v2/offers/collection/{collection_slug}/traits][%d] getTraitOffersV2NotFound ", 404)
}

func (o *GetTraitOffersV2NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTraitOffersV2InternalServerError creates a GetTraitOffersV2InternalServerError with default headers values
func NewGetTraitOffersV2InternalServerError() *GetTraitOffersV2InternalServerError {
	return &GetTraitOffersV2InternalServerError{}
}

/*
GetTraitOffersV2InternalServerError describes a response with status code 500, with default header values.

Internal server error. Please open a support ticket so OpenSea can investigate.
*/
type GetTraitOffersV2InternalServerError struct {
}

// IsSuccess returns true when this get trait offers v2 internal server error response has a 2xx status code
func (o *GetTraitOffersV2InternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get trait offers v2 internal server error response has a 3xx status code
func (o *GetTraitOffersV2InternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get trait offers v2 internal server error response has a 4xx status code
func (o *GetTraitOffersV2InternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get trait offers v2 internal server error response has a 5xx status code
func (o *GetTraitOffersV2InternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get trait offers v2 internal server error response a status code equal to that given
func (o *GetTraitOffersV2InternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get trait offers v2 internal server error response
func (o *GetTraitOffersV2InternalServerError) Code() int {
	return 500
}

func (o *GetTraitOffersV2InternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v2/offers/collection/{collection_slug}/traits][%d] getTraitOffersV2InternalServerError ", 500)
}

func (o *GetTraitOffersV2InternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v2/offers/collection/{collection_slug}/traits][%d] getTraitOffersV2InternalServerError ", 500)
}

func (o *GetTraitOffersV2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
