// Code generated by go-swagger; DO NOT EDIT.

package transaction_endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCollectionOffersV2Params creates a new GetCollectionOffersV2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCollectionOffersV2Params() *GetCollectionOffersV2Params {
	return &GetCollectionOffersV2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCollectionOffersV2ParamsWithTimeout creates a new GetCollectionOffersV2Params object
// with the ability to set a timeout on a request.
func NewGetCollectionOffersV2ParamsWithTimeout(timeout time.Duration) *GetCollectionOffersV2Params {
	return &GetCollectionOffersV2Params{
		timeout: timeout,
	}
}

// NewGetCollectionOffersV2ParamsWithContext creates a new GetCollectionOffersV2Params object
// with the ability to set a context for a request.
func NewGetCollectionOffersV2ParamsWithContext(ctx context.Context) *GetCollectionOffersV2Params {
	return &GetCollectionOffersV2Params{
		Context: ctx,
	}
}

// NewGetCollectionOffersV2ParamsWithHTTPClient creates a new GetCollectionOffersV2Params object
// with the ability to set a custom HTTPClient for a request.
func NewGetCollectionOffersV2ParamsWithHTTPClient(client *http.Client) *GetCollectionOffersV2Params {
	return &GetCollectionOffersV2Params{
		HTTPClient: client,
	}
}

/*
GetCollectionOffersV2Params contains all the parameters to send to the API endpoint

	for the get collection offers v2 operation.

	Typically these are written to a http.Request.
*/
type GetCollectionOffersV2Params struct {

	/* CollectionSlug.

	   Unique string to identify a collection on OpenSea. This can be found by visiting the collection on the OpenSea website and noting the last path parameter.
	*/
	CollectionSlug string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get collection offers v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollectionOffersV2Params) WithDefaults() *GetCollectionOffersV2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get collection offers v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollectionOffersV2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get collection offers v2 params
func (o *GetCollectionOffersV2Params) WithTimeout(timeout time.Duration) *GetCollectionOffersV2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get collection offers v2 params
func (o *GetCollectionOffersV2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get collection offers v2 params
func (o *GetCollectionOffersV2Params) WithContext(ctx context.Context) *GetCollectionOffersV2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get collection offers v2 params
func (o *GetCollectionOffersV2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get collection offers v2 params
func (o *GetCollectionOffersV2Params) WithHTTPClient(client *http.Client) *GetCollectionOffersV2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get collection offers v2 params
func (o *GetCollectionOffersV2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCollectionSlug adds the collectionSlug to the get collection offers v2 params
func (o *GetCollectionOffersV2Params) WithCollectionSlug(collectionSlug string) *GetCollectionOffersV2Params {
	o.SetCollectionSlug(collectionSlug)
	return o
}

// SetCollectionSlug adds the collectionSlug to the get collection offers v2 params
func (o *GetCollectionOffersV2Params) SetCollectionSlug(collectionSlug string) {
	o.CollectionSlug = collectionSlug
}

// WriteToRequest writes these params to a swagger request
func (o *GetCollectionOffersV2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param collection_slug
	if err := r.SetPathParam("collection_slug", o.CollectionSlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
