// Code generated by go-swagger; DO NOT EDIT.

package transaction_endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/go-opensea/opensea/models"
)

// PostOfferReader is a Reader for the PostOffer structure.
type PostOfferReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostOfferReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostOfferOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostOfferBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostOfferInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostOfferOK creates a PostOfferOK with default headers values
func NewPostOfferOK() *PostOfferOK {
	return &PostOfferOK{}
}

/*
PostOfferOK describes a response with status code 200, with default header values.

PostOfferOK post offer o k
*/
type PostOfferOK struct {
	Payload *models.CreateOfferResponse
}

// IsSuccess returns true when this post offer o k response has a 2xx status code
func (o *PostOfferOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post offer o k response has a 3xx status code
func (o *PostOfferOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post offer o k response has a 4xx status code
func (o *PostOfferOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post offer o k response has a 5xx status code
func (o *PostOfferOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post offer o k response a status code equal to that given
func (o *PostOfferOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post offer o k response
func (o *PostOfferOK) Code() int {
	return 200
}

func (o *PostOfferOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/orders/{chain}/{protocol}/offers][%d] postOfferOK  %+v", 200, o.Payload)
}

func (o *PostOfferOK) String() string {
	return fmt.Sprintf("[POST /api/v2/orders/{chain}/{protocol}/offers][%d] postOfferOK  %+v", 200, o.Payload)
}

func (o *PostOfferOK) GetPayload() *models.CreateOfferResponse {
	return o.Payload
}

func (o *PostOfferOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateOfferResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostOfferBadRequest creates a PostOfferBadRequest with default headers values
func NewPostOfferBadRequest() *PostOfferBadRequest {
	return &PostOfferBadRequest{}
}

/*
PostOfferBadRequest describes a response with status code 400, with default header values.

For error reasons, review the response data.
*/
type PostOfferBadRequest struct {
}

// IsSuccess returns true when this post offer bad request response has a 2xx status code
func (o *PostOfferBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post offer bad request response has a 3xx status code
func (o *PostOfferBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post offer bad request response has a 4xx status code
func (o *PostOfferBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post offer bad request response has a 5xx status code
func (o *PostOfferBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post offer bad request response a status code equal to that given
func (o *PostOfferBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post offer bad request response
func (o *PostOfferBadRequest) Code() int {
	return 400
}

func (o *PostOfferBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/orders/{chain}/{protocol}/offers][%d] postOfferBadRequest ", 400)
}

func (o *PostOfferBadRequest) String() string {
	return fmt.Sprintf("[POST /api/v2/orders/{chain}/{protocol}/offers][%d] postOfferBadRequest ", 400)
}

func (o *PostOfferBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostOfferInternalServerError creates a PostOfferInternalServerError with default headers values
func NewPostOfferInternalServerError() *PostOfferInternalServerError {
	return &PostOfferInternalServerError{}
}

/*
PostOfferInternalServerError describes a response with status code 500, with default header values.

Internal server error. Please open a support ticket so OpenSea can investigate.
*/
type PostOfferInternalServerError struct {
}

// IsSuccess returns true when this post offer internal server error response has a 2xx status code
func (o *PostOfferInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post offer internal server error response has a 3xx status code
func (o *PostOfferInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post offer internal server error response has a 4xx status code
func (o *PostOfferInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post offer internal server error response has a 5xx status code
func (o *PostOfferInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post offer internal server error response a status code equal to that given
func (o *PostOfferInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post offer internal server error response
func (o *PostOfferInternalServerError) Code() int {
	return 500
}

func (o *PostOfferInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v2/orders/{chain}/{protocol}/offers][%d] postOfferInternalServerError ", 500)
}

func (o *PostOfferInternalServerError) String() string {
	return fmt.Sprintf("[POST /api/v2/orders/{chain}/{protocol}/offers][%d] postOfferInternalServerError ", 500)
}

func (o *PostOfferInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
