// Code generated by go-swagger; DO NOT EDIT.

package transaction_endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/go-opensea/opensea/models"
)

// PostListingReader is a Reader for the PostListing structure.
type PostListingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostListingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostListingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostListingBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostListingInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostListingOK creates a PostListingOK with default headers values
func NewPostListingOK() *PostListingOK {
	return &PostListingOK{}
}

/*
PostListingOK describes a response with status code 200, with default header values.

PostListingOK post listing o k
*/
type PostListingOK struct {
	Payload *models.CreateListingResponse
}

// IsSuccess returns true when this post listing o k response has a 2xx status code
func (o *PostListingOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post listing o k response has a 3xx status code
func (o *PostListingOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post listing o k response has a 4xx status code
func (o *PostListingOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post listing o k response has a 5xx status code
func (o *PostListingOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post listing o k response a status code equal to that given
func (o *PostListingOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post listing o k response
func (o *PostListingOK) Code() int {
	return 200
}

func (o *PostListingOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/orders/{chain}/{protocol}/listings][%d] postListingOK  %+v", 200, o.Payload)
}

func (o *PostListingOK) String() string {
	return fmt.Sprintf("[POST /api/v2/orders/{chain}/{protocol}/listings][%d] postListingOK  %+v", 200, o.Payload)
}

func (o *PostListingOK) GetPayload() *models.CreateListingResponse {
	return o.Payload
}

func (o *PostListingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateListingResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostListingBadRequest creates a PostListingBadRequest with default headers values
func NewPostListingBadRequest() *PostListingBadRequest {
	return &PostListingBadRequest{}
}

/*
PostListingBadRequest describes a response with status code 400, with default header values.

For error reasons, review the response data.
*/
type PostListingBadRequest struct {
}

// IsSuccess returns true when this post listing bad request response has a 2xx status code
func (o *PostListingBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post listing bad request response has a 3xx status code
func (o *PostListingBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post listing bad request response has a 4xx status code
func (o *PostListingBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post listing bad request response has a 5xx status code
func (o *PostListingBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post listing bad request response a status code equal to that given
func (o *PostListingBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post listing bad request response
func (o *PostListingBadRequest) Code() int {
	return 400
}

func (o *PostListingBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/orders/{chain}/{protocol}/listings][%d] postListingBadRequest ", 400)
}

func (o *PostListingBadRequest) String() string {
	return fmt.Sprintf("[POST /api/v2/orders/{chain}/{protocol}/listings][%d] postListingBadRequest ", 400)
}

func (o *PostListingBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostListingInternalServerError creates a PostListingInternalServerError with default headers values
func NewPostListingInternalServerError() *PostListingInternalServerError {
	return &PostListingInternalServerError{}
}

/*
PostListingInternalServerError describes a response with status code 500, with default header values.

Internal server error. Please open a support ticket so OpenSea can investigate.
*/
type PostListingInternalServerError struct {
}

// IsSuccess returns true when this post listing internal server error response has a 2xx status code
func (o *PostListingInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post listing internal server error response has a 3xx status code
func (o *PostListingInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post listing internal server error response has a 4xx status code
func (o *PostListingInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post listing internal server error response has a 5xx status code
func (o *PostListingInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post listing internal server error response a status code equal to that given
func (o *PostListingInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post listing internal server error response
func (o *PostListingInternalServerError) Code() int {
	return 500
}

func (o *PostListingInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v2/orders/{chain}/{protocol}/listings][%d] postListingInternalServerError ", 500)
}

func (o *PostListingInternalServerError) String() string {
	return fmt.Sprintf("[POST /api/v2/orders/{chain}/{protocol}/listings][%d] postListingInternalServerError ", 500)
}

func (o *PostListingInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
