// Code generated by go-swagger; DO NOT EDIT.

package transaction_endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/go-opensea/opensea/models"
)

// PostCriteriaOfferV2Reader is a Reader for the PostCriteriaOfferV2 structure.
type PostCriteriaOfferV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCriteriaOfferV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostCriteriaOfferV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostCriteriaOfferV2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostCriteriaOfferV2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostCriteriaOfferV2OK creates a PostCriteriaOfferV2OK with default headers values
func NewPostCriteriaOfferV2OK() *PostCriteriaOfferV2OK {
	return &PostCriteriaOfferV2OK{}
}

/*
PostCriteriaOfferV2OK describes a response with status code 200, with default header values.

PostCriteriaOfferV2OK post criteria offer v2 o k
*/
type PostCriteriaOfferV2OK struct {
	Payload *models.Offer
}

// IsSuccess returns true when this post criteria offer v2 o k response has a 2xx status code
func (o *PostCriteriaOfferV2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post criteria offer v2 o k response has a 3xx status code
func (o *PostCriteriaOfferV2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post criteria offer v2 o k response has a 4xx status code
func (o *PostCriteriaOfferV2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post criteria offer v2 o k response has a 5xx status code
func (o *PostCriteriaOfferV2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this post criteria offer v2 o k response a status code equal to that given
func (o *PostCriteriaOfferV2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post criteria offer v2 o k response
func (o *PostCriteriaOfferV2OK) Code() int {
	return 200
}

func (o *PostCriteriaOfferV2OK) Error() string {
	return fmt.Sprintf("[POST /api/v2/offers][%d] postCriteriaOfferV2OK  %+v", 200, o.Payload)
}

func (o *PostCriteriaOfferV2OK) String() string {
	return fmt.Sprintf("[POST /api/v2/offers][%d] postCriteriaOfferV2OK  %+v", 200, o.Payload)
}

func (o *PostCriteriaOfferV2OK) GetPayload() *models.Offer {
	return o.Payload
}

func (o *PostCriteriaOfferV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Offer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostCriteriaOfferV2BadRequest creates a PostCriteriaOfferV2BadRequest with default headers values
func NewPostCriteriaOfferV2BadRequest() *PostCriteriaOfferV2BadRequest {
	return &PostCriteriaOfferV2BadRequest{}
}

/*
PostCriteriaOfferV2BadRequest describes a response with status code 400, with default header values.

For error reasons, review the response data.
*/
type PostCriteriaOfferV2BadRequest struct {
}

// IsSuccess returns true when this post criteria offer v2 bad request response has a 2xx status code
func (o *PostCriteriaOfferV2BadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post criteria offer v2 bad request response has a 3xx status code
func (o *PostCriteriaOfferV2BadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post criteria offer v2 bad request response has a 4xx status code
func (o *PostCriteriaOfferV2BadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post criteria offer v2 bad request response has a 5xx status code
func (o *PostCriteriaOfferV2BadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post criteria offer v2 bad request response a status code equal to that given
func (o *PostCriteriaOfferV2BadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post criteria offer v2 bad request response
func (o *PostCriteriaOfferV2BadRequest) Code() int {
	return 400
}

func (o *PostCriteriaOfferV2BadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/offers][%d] postCriteriaOfferV2BadRequest ", 400)
}

func (o *PostCriteriaOfferV2BadRequest) String() string {
	return fmt.Sprintf("[POST /api/v2/offers][%d] postCriteriaOfferV2BadRequest ", 400)
}

func (o *PostCriteriaOfferV2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCriteriaOfferV2InternalServerError creates a PostCriteriaOfferV2InternalServerError with default headers values
func NewPostCriteriaOfferV2InternalServerError() *PostCriteriaOfferV2InternalServerError {
	return &PostCriteriaOfferV2InternalServerError{}
}

/*
PostCriteriaOfferV2InternalServerError describes a response with status code 500, with default header values.

Internal server error. Please open a support ticket so OpenSea can investigate.
*/
type PostCriteriaOfferV2InternalServerError struct {
}

// IsSuccess returns true when this post criteria offer v2 internal server error response has a 2xx status code
func (o *PostCriteriaOfferV2InternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post criteria offer v2 internal server error response has a 3xx status code
func (o *PostCriteriaOfferV2InternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post criteria offer v2 internal server error response has a 4xx status code
func (o *PostCriteriaOfferV2InternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post criteria offer v2 internal server error response has a 5xx status code
func (o *PostCriteriaOfferV2InternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post criteria offer v2 internal server error response a status code equal to that given
func (o *PostCriteriaOfferV2InternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post criteria offer v2 internal server error response
func (o *PostCriteriaOfferV2InternalServerError) Code() int {
	return 500
}

func (o *PostCriteriaOfferV2InternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v2/offers][%d] postCriteriaOfferV2InternalServerError ", 500)
}

func (o *PostCriteriaOfferV2InternalServerError) String() string {
	return fmt.Sprintf("[POST /api/v2/offers][%d] postCriteriaOfferV2InternalServerError ", 500)
}

func (o *PostCriteriaOfferV2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
