// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BuildOffer BuildOffer
//
// swagger:model BuildOffer
type BuildOffer struct {

	// Encoded Token Ids
	//
	// Represents a list of token ids which can be used to fulfill the criteria offer. When decoded using the provided SDK function, developers can now see a list of all tokens that could be used to fulfill the offer.
	EncodedTokenIds string `json:"encoded_token_ids,omitempty"`

	// Partialparameters
	//
	// Partial set of Seaport Order Parameters
	// Required: true
	PartialParameters struct {
		PartialParameters
	} `json:"partialParameters"`
}

// Validate validates this build offer
func (m *BuildOffer) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePartialParameters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BuildOffer) validatePartialParameters(formats strfmt.Registry) error {

	return nil
}

// ContextValidate validate this build offer based on the context it is used
func (m *BuildOffer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePartialParameters(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BuildOffer) contextValidatePartialParameters(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *BuildOffer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BuildOffer) UnmarshalBinary(b []byte) error {
	var res BuildOffer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
