// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ConsiderationInput ConsiderationInput
//
// swagger:model ConsiderationInput
type ConsiderationInput struct {

	// Asset Contract Address
	// Required: true
	AssetContractAddress *string `json:"asset_contract_address"`

	// Token Id
	//
	// NFT Token ID which will be used to fulfill the offer.
	// Required: true
	TokenID *string `json:"token_id"`
}

// Validate validates this consideration input
func (m *ConsiderationInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAssetContractAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTokenID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConsiderationInput) validateAssetContractAddress(formats strfmt.Registry) error {

	if err := validate.Required("asset_contract_address", "body", m.AssetContractAddress); err != nil {
		return err
	}

	return nil
}

func (m *ConsiderationInput) validateTokenID(formats strfmt.Registry) error {

	if err := validate.Required("token_id", "body", m.TokenID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this consideration input based on context it is used
func (m *ConsiderationInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConsiderationInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConsiderationInput) UnmarshalBinary(b []byte) error {
	var res ConsiderationInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
