// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// CoreTypesOrderType OrderType
//
// basic - Quantities are fixed. Used for fixed price listings and offers.
// dutch - The quantity represents the starting price.
// english - The quantity represents the minimum price.
// criteria - The items that are accepted by this offer will be found in the criteria fields.
//
// swagger:model core__types__OrderType
type CoreTypesOrderType interface{}
