// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FulfillmentOutput FulfillmentOutput
//
// swagger:model FulfillmentOutput
type FulfillmentOutput struct {

	// Fulfillment Data
	//
	// All the information, including signatures, needed to fulfill an order directly onchain.
	// Required: true
	FulfillmentData struct {
		FulfillmentData
	} `json:"fulfillment_data"`

	// Protocol
	//
	// Exchange contract address. Must be one of ['0x00000000000000adc04c56bf30ac9d3c0aaf14dc']
	// Required: true
	Protocol *string `json:"protocol"`
}

// Validate validates this fulfillment output
func (m *FulfillmentOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFulfillmentData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProtocol(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FulfillmentOutput) validateFulfillmentData(formats strfmt.Registry) error {

	return nil
}

func (m *FulfillmentOutput) validateProtocol(formats strfmt.Registry) error {

	if err := validate.Required("protocol", "body", m.Protocol); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this fulfillment output based on the context it is used
func (m *FulfillmentOutput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFulfillmentData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FulfillmentOutput) contextValidateFulfillmentData(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *FulfillmentOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FulfillmentOutput) UnmarshalBinary(b []byte) error {
	var res FulfillmentOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
