// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ListEventsResponse ListEventsResponse
//
// swagger:model ListEventsResponse
type ListEventsResponse struct {

	// Events
	// Required: true
	AssetEvents []interface{} `json:"asset_events"`

	// Next
	//
	// Cursor for the next page of results
	// Required: true
	Next *string `json:"next"`
}

// Validate validates this list events response
func (m *ListEventsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAssetEvents(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNext(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ListEventsResponse) validateAssetEvents(formats strfmt.Registry) error {

	if err := validate.Required("asset_events", "body", m.AssetEvents); err != nil {
		return err
	}

	return nil
}

func (m *ListEventsResponse) validateNext(formats strfmt.Registry) error {

	if err := validate.Required("next", "body", m.Next); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this list events response based on context it is used
func (m *ListEventsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ListEventsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListEventsResponse) UnmarshalBinary(b []byte) error {
	var res ListEventsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
