// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrderInputWithProtocol OrderInputWithProtocol
//
// swagger:model OrderInputWithProtocol
type OrderInputWithProtocol struct {

	// Order Components
	// Required: true
	Parameters struct {
		OrderInputComponents
	} `json:"parameters"`

	// Protocol Address
	//
	// Exchange contract address. Must be one of ['0x00000000000000adc04c56bf30ac9d3c0aaf14dc']
	// Required: true
	ProtocolAddress *string `json:"protocol_address"`

	// Signature
	//
	// Signature of the signed type data represented by the parameters field.
	// Required: true
	Signature *string `json:"signature"`
}

// Validate validates this order input with protocol
func (m *OrderInputWithProtocol) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateParameters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProtocolAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSignature(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderInputWithProtocol) validateParameters(formats strfmt.Registry) error {

	return nil
}

func (m *OrderInputWithProtocol) validateProtocolAddress(formats strfmt.Registry) error {

	if err := validate.Required("protocol_address", "body", m.ProtocolAddress); err != nil {
		return err
	}

	return nil
}

func (m *OrderInputWithProtocol) validateSignature(formats strfmt.Registry) error {

	if err := validate.Required("signature", "body", m.Signature); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this order input with protocol based on the context it is used
func (m *OrderInputWithProtocol) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateParameters(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderInputWithProtocol) contextValidateParameters(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *OrderInputWithProtocol) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderInputWithProtocol) UnmarshalBinary(b []byte) error {
	var res OrderInputWithProtocol
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
