// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// RedemptionEventModelEventTypeEnum redemption event model event type enum
//
// swagger:model RedemptionEventModelEventTypeEnum
type RedemptionEventModelEventTypeEnum string

func NewRedemptionEventModelEventTypeEnum(value RedemptionEventModelEventTypeEnum) *RedemptionEventModelEventTypeEnum {
	return &value
}

// Pointer returns a pointer to a freshly-allocated RedemptionEventModelEventTypeEnum.
func (m RedemptionEventModelEventTypeEnum) Pointer() *RedemptionEventModelEventTypeEnum {
	return &m
}

const (

	// RedemptionEventModelEventTypeEnumRedemption captures enum value "redemption"
	RedemptionEventModelEventTypeEnumRedemption RedemptionEventModelEventTypeEnum = "redemption"
)

// for schema
var redemptionEventModelEventTypeEnumEnum []interface{}

func init() {
	var res []RedemptionEventModelEventTypeEnum
	if err := json.Unmarshal([]byte(`["redemption"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		redemptionEventModelEventTypeEnumEnum = append(redemptionEventModelEventTypeEnumEnum, v)
	}
}

func (m RedemptionEventModelEventTypeEnum) validateRedemptionEventModelEventTypeEnumEnum(path, location string, value RedemptionEventModelEventTypeEnum) error {
	if err := validate.EnumCase(path, location, value, redemptionEventModelEventTypeEnumEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this redemption event model event type enum
func (m RedemptionEventModelEventTypeEnum) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateRedemptionEventModelEventTypeEnumEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this redemption event model event type enum based on context it is used
func (m RedemptionEventModelEventTypeEnum) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
