// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SimpleFee simple fee
//
// swagger:model SimpleFee
type SimpleFee struct {

	// account
	// Required: true
	// Read Only: true
	Account struct {
		SimpleAccount
	} `json:"account"`

	// basis points
	// Required: true
	BasisPoints *string `json:"basis_points"`
}

// Validate validates this simple fee
func (m *SimpleFee) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBasisPoints(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SimpleFee) validateAccount(formats strfmt.Registry) error {

	return nil
}

func (m *SimpleFee) validateBasisPoints(formats strfmt.Registry) error {

	if err := validate.Required("basis_points", "body", m.BasisPoints); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this simple fee based on the context it is used
func (m *SimpleFee) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAccount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SimpleFee) contextValidateAccount(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *SimpleFee) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SimpleFee) UnmarshalBinary(b []byte) error {
	var res SimpleFee
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
