// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SocialMediaAccountModel SocialMediaAccountModel
//
// swagger:model SocialMediaAccountModel
type SocialMediaAccountModel struct {

	// Platform
	//
	// The social media platform, e.g. twitter or instagram
	// Required: true
	Platform *string `json:"platform"`

	// Username
	//
	// The username for the social media platform
	// Required: true
	Username *string `json:"username"`
}

// Validate validates this social media account model
func (m *SocialMediaAccountModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePlatform(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUsername(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SocialMediaAccountModel) validatePlatform(formats strfmt.Registry) error {

	if err := validate.Required("platform", "body", m.Platform); err != nil {
		return err
	}

	return nil
}

func (m *SocialMediaAccountModel) validateUsername(formats strfmt.Registry) error {

	if err := validate.Required("username", "body", m.Username); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this social media account model based on context it is used
func (m *SocialMediaAccountModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SocialMediaAccountModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SocialMediaAccountModel) UnmarshalBinary(b []byte) error {
	var res SocialMediaAccountModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
