// Code generated by go-swagger; DO NOT EDIT.

package n_f_t_endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetContractParams creates a new GetContractParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetContractParams() *GetContractParams {
	return &GetContractParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetContractParamsWithTimeout creates a new GetContractParams object
// with the ability to set a timeout on a request.
func NewGetContractParamsWithTimeout(timeout time.Duration) *GetContractParams {
	return &GetContractParams{
		timeout: timeout,
	}
}

// NewGetContractParamsWithContext creates a new GetContractParams object
// with the ability to set a context for a request.
func NewGetContractParamsWithContext(ctx context.Context) *GetContractParams {
	return &GetContractParams{
		Context: ctx,
	}
}

// NewGetContractParamsWithHTTPClient creates a new GetContractParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetContractParamsWithHTTPClient(client *http.Client) *GetContractParams {
	return &GetContractParams{
		HTTPClient: client,
	}
}

/*
GetContractParams contains all the parameters to send to the API endpoint

	for the get contract operation.

	Typically these are written to a http.Request.
*/
type GetContractParams struct {

	/* Address.

	   The unique public blockchain identifier for the contract or wallet.
	*/
	Address string

	/* Chain.

	   The blockchain on which to filter the results.
	*/
	Chain string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get contract params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetContractParams) WithDefaults() *GetContractParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get contract params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetContractParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get contract params
func (o *GetContractParams) WithTimeout(timeout time.Duration) *GetContractParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get contract params
func (o *GetContractParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get contract params
func (o *GetContractParams) WithContext(ctx context.Context) *GetContractParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get contract params
func (o *GetContractParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get contract params
func (o *GetContractParams) WithHTTPClient(client *http.Client) *GetContractParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get contract params
func (o *GetContractParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the get contract params
func (o *GetContractParams) WithAddress(address string) *GetContractParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the get contract params
func (o *GetContractParams) SetAddress(address string) {
	o.Address = address
}

// WithChain adds the chain to the get contract params
func (o *GetContractParams) WithChain(chain string) *GetContractParams {
	o.SetChain(chain)
	return o
}

// SetChain adds the chain to the get contract params
func (o *GetContractParams) SetChain(chain string) {
	o.Chain = chain
}

// WriteToRequest writes these params to a swagger request
func (o *GetContractParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}

	// path param chain
	if err := r.SetPathParam("chain", o.Chain); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
