// Code generated by go-swagger; DO NOT EDIT.

package n_f_t_endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/go-opensea/opensea/models"
)

// GetAccountReader is a Reader for the GetAccount structure.
type GetAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAccountBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAccountInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAccountOK creates a GetAccountOK with default headers values
func NewGetAccountOK() *GetAccountOK {
	return &GetAccountOK{}
}

/*
GetAccountOK describes a response with status code 200, with default header values.

GetAccountOK get account o k
*/
type GetAccountOK struct {
	Payload *models.DetailedAccountDataModel
}

// IsSuccess returns true when this get account o k response has a 2xx status code
func (o *GetAccountOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get account o k response has a 3xx status code
func (o *GetAccountOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get account o k response has a 4xx status code
func (o *GetAccountOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get account o k response has a 5xx status code
func (o *GetAccountOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get account o k response a status code equal to that given
func (o *GetAccountOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get account o k response
func (o *GetAccountOK) Code() int {
	return 200
}

func (o *GetAccountOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/accounts/{address}][%d] getAccountOK  %+v", 200, o.Payload)
}

func (o *GetAccountOK) String() string {
	return fmt.Sprintf("[GET /api/v2/accounts/{address}][%d] getAccountOK  %+v", 200, o.Payload)
}

func (o *GetAccountOK) GetPayload() *models.DetailedAccountDataModel {
	return o.Payload
}

func (o *GetAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DetailedAccountDataModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccountBadRequest creates a GetAccountBadRequest with default headers values
func NewGetAccountBadRequest() *GetAccountBadRequest {
	return &GetAccountBadRequest{}
}

/*
GetAccountBadRequest describes a response with status code 400, with default header values.

Returned if the Account does not exist or can not be parsed.
*/
type GetAccountBadRequest struct {
}

// IsSuccess returns true when this get account bad request response has a 2xx status code
func (o *GetAccountBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get account bad request response has a 3xx status code
func (o *GetAccountBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get account bad request response has a 4xx status code
func (o *GetAccountBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get account bad request response has a 5xx status code
func (o *GetAccountBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get account bad request response a status code equal to that given
func (o *GetAccountBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get account bad request response
func (o *GetAccountBadRequest) Code() int {
	return 400
}

func (o *GetAccountBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/accounts/{address}][%d] getAccountBadRequest ", 400)
}

func (o *GetAccountBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v2/accounts/{address}][%d] getAccountBadRequest ", 400)
}

func (o *GetAccountBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAccountInternalServerError creates a GetAccountInternalServerError with default headers values
func NewGetAccountInternalServerError() *GetAccountInternalServerError {
	return &GetAccountInternalServerError{}
}

/*
GetAccountInternalServerError describes a response with status code 500, with default header values.

Internal server error. Please open a support ticket so OpenSea can investigate.
*/
type GetAccountInternalServerError struct {
}

// IsSuccess returns true when this get account internal server error response has a 2xx status code
func (o *GetAccountInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get account internal server error response has a 3xx status code
func (o *GetAccountInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get account internal server error response has a 4xx status code
func (o *GetAccountInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get account internal server error response has a 5xx status code
func (o *GetAccountInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get account internal server error response a status code equal to that given
func (o *GetAccountInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get account internal server error response
func (o *GetAccountInternalServerError) Code() int {
	return 500
}

func (o *GetAccountInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v2/accounts/{address}][%d] getAccountInternalServerError ", 500)
}

func (o *GetAccountInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v2/accounts/{address}][%d] getAccountInternalServerError ", 500)
}

func (o *GetAccountInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
