// Code generated by go-swagger; DO NOT EDIT.

package n_f_t_endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetNftParams creates a new GetNftParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetNftParams() *GetNftParams {
	return &GetNftParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetNftParamsWithTimeout creates a new GetNftParams object
// with the ability to set a timeout on a request.
func NewGetNftParamsWithTimeout(timeout time.Duration) *GetNftParams {
	return &GetNftParams{
		timeout: timeout,
	}
}

// NewGetNftParamsWithContext creates a new GetNftParams object
// with the ability to set a context for a request.
func NewGetNftParamsWithContext(ctx context.Context) *GetNftParams {
	return &GetNftParams{
		Context: ctx,
	}
}

// NewGetNftParamsWithHTTPClient creates a new GetNftParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetNftParamsWithHTTPClient(client *http.Client) *GetNftParams {
	return &GetNftParams{
		HTTPClient: client,
	}
}

/*
GetNftParams contains all the parameters to send to the API endpoint

	for the get nft operation.

	Typically these are written to a http.Request.
*/
type GetNftParams struct {

	/* Address.

	   The unique public blockchain identifier for the contract or wallet.
	*/
	Address string

	/* Chain.

	   The blockchain on which to filter the results.
	*/
	Chain string

	/* Identifier.

	   The NFT token id.
	*/
	Identifier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get nft params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNftParams) WithDefaults() *GetNftParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get nft params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNftParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get nft params
func (o *GetNftParams) WithTimeout(timeout time.Duration) *GetNftParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get nft params
func (o *GetNftParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get nft params
func (o *GetNftParams) WithContext(ctx context.Context) *GetNftParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get nft params
func (o *GetNftParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get nft params
func (o *GetNftParams) WithHTTPClient(client *http.Client) *GetNftParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get nft params
func (o *GetNftParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the get nft params
func (o *GetNftParams) WithAddress(address string) *GetNftParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the get nft params
func (o *GetNftParams) SetAddress(address string) {
	o.Address = address
}

// WithChain adds the chain to the get nft params
func (o *GetNftParams) WithChain(chain string) *GetNftParams {
	o.SetChain(chain)
	return o
}

// SetChain adds the chain to the get nft params
func (o *GetNftParams) SetChain(chain string) {
	o.Chain = chain
}

// WithIdentifier adds the identifier to the get nft params
func (o *GetNftParams) WithIdentifier(identifier string) *GetNftParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the get nft params
func (o *GetNftParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WriteToRequest writes these params to a swagger request
func (o *GetNftParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}

	// path param chain
	if err := r.SetPathParam("chain", o.Chain); err != nil {
		return err
	}

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
