// Code generated by go-swagger; DO NOT EDIT.

package n_f_t_endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/go-opensea/opensea/models"
)

// ListNftsByCollectionReader is a Reader for the ListNftsByCollection structure.
type ListNftsByCollectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListNftsByCollectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListNftsByCollectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListNftsByCollectionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListNftsByCollectionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListNftsByCollectionOK creates a ListNftsByCollectionOK with default headers values
func NewListNftsByCollectionOK() *ListNftsByCollectionOK {
	return &ListNftsByCollectionOK{}
}

/*
ListNftsByCollectionOK describes a response with status code 200, with default header values.

ListNftsByCollectionOK list nfts by collection o k
*/
type ListNftsByCollectionOK struct {
	Payload *models.ListNftsResponse
}

// IsSuccess returns true when this list nfts by collection o k response has a 2xx status code
func (o *ListNftsByCollectionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list nfts by collection o k response has a 3xx status code
func (o *ListNftsByCollectionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list nfts by collection o k response has a 4xx status code
func (o *ListNftsByCollectionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list nfts by collection o k response has a 5xx status code
func (o *ListNftsByCollectionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list nfts by collection o k response a status code equal to that given
func (o *ListNftsByCollectionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list nfts by collection o k response
func (o *ListNftsByCollectionOK) Code() int {
	return 200
}

func (o *ListNftsByCollectionOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/collection/{collection_slug}/nfts][%d] listNftsByCollectionOK  %+v", 200, o.Payload)
}

func (o *ListNftsByCollectionOK) String() string {
	return fmt.Sprintf("[GET /api/v2/collection/{collection_slug}/nfts][%d] listNftsByCollectionOK  %+v", 200, o.Payload)
}

func (o *ListNftsByCollectionOK) GetPayload() *models.ListNftsResponse {
	return o.Payload
}

func (o *ListNftsByCollectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListNftsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListNftsByCollectionBadRequest creates a ListNftsByCollectionBadRequest with default headers values
func NewListNftsByCollectionBadRequest() *ListNftsByCollectionBadRequest {
	return &ListNftsByCollectionBadRequest{}
}

/*
ListNftsByCollectionBadRequest describes a response with status code 400, with default header values.

For error reasons, review the response data.
*/
type ListNftsByCollectionBadRequest struct {
}

// IsSuccess returns true when this list nfts by collection bad request response has a 2xx status code
func (o *ListNftsByCollectionBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list nfts by collection bad request response has a 3xx status code
func (o *ListNftsByCollectionBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list nfts by collection bad request response has a 4xx status code
func (o *ListNftsByCollectionBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list nfts by collection bad request response has a 5xx status code
func (o *ListNftsByCollectionBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list nfts by collection bad request response a status code equal to that given
func (o *ListNftsByCollectionBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list nfts by collection bad request response
func (o *ListNftsByCollectionBadRequest) Code() int {
	return 400
}

func (o *ListNftsByCollectionBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/collection/{collection_slug}/nfts][%d] listNftsByCollectionBadRequest ", 400)
}

func (o *ListNftsByCollectionBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v2/collection/{collection_slug}/nfts][%d] listNftsByCollectionBadRequest ", 400)
}

func (o *ListNftsByCollectionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListNftsByCollectionInternalServerError creates a ListNftsByCollectionInternalServerError with default headers values
func NewListNftsByCollectionInternalServerError() *ListNftsByCollectionInternalServerError {
	return &ListNftsByCollectionInternalServerError{}
}

/*
ListNftsByCollectionInternalServerError describes a response with status code 500, with default header values.

Internal server error. Please open a support ticket so OpenSea can investigate.
*/
type ListNftsByCollectionInternalServerError struct {
}

// IsSuccess returns true when this list nfts by collection internal server error response has a 2xx status code
func (o *ListNftsByCollectionInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list nfts by collection internal server error response has a 3xx status code
func (o *ListNftsByCollectionInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list nfts by collection internal server error response has a 4xx status code
func (o *ListNftsByCollectionInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list nfts by collection internal server error response has a 5xx status code
func (o *ListNftsByCollectionInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list nfts by collection internal server error response a status code equal to that given
func (o *ListNftsByCollectionInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list nfts by collection internal server error response
func (o *ListNftsByCollectionInternalServerError) Code() int {
	return 500
}

func (o *ListNftsByCollectionInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v2/collection/{collection_slug}/nfts][%d] listNftsByCollectionInternalServerError ", 500)
}

func (o *ListNftsByCollectionInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v2/collection/{collection_slug}/nfts][%d] listNftsByCollectionInternalServerError ", 500)
}

func (o *ListNftsByCollectionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
