// Code generated by go-swagger; DO NOT EDIT.

package n_f_t_endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/go-opensea/opensea/models"
)

// ListCollectionsReader is a Reader for the ListCollections structure.
type ListCollectionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListCollectionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListCollectionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListCollectionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListCollectionsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListCollectionsOK creates a ListCollectionsOK with default headers values
func NewListCollectionsOK() *ListCollectionsOK {
	return &ListCollectionsOK{}
}

/*
ListCollectionsOK describes a response with status code 200, with default header values.

ListCollectionsOK list collections o k
*/
type ListCollectionsOK struct {
	Payload *models.ListCollectionsResponse
}

// IsSuccess returns true when this list collections o k response has a 2xx status code
func (o *ListCollectionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list collections o k response has a 3xx status code
func (o *ListCollectionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list collections o k response has a 4xx status code
func (o *ListCollectionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list collections o k response has a 5xx status code
func (o *ListCollectionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list collections o k response a status code equal to that given
func (o *ListCollectionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list collections o k response
func (o *ListCollectionsOK) Code() int {
	return 200
}

func (o *ListCollectionsOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/collections][%d] listCollectionsOK  %+v", 200, o.Payload)
}

func (o *ListCollectionsOK) String() string {
	return fmt.Sprintf("[GET /api/v2/collections][%d] listCollectionsOK  %+v", 200, o.Payload)
}

func (o *ListCollectionsOK) GetPayload() *models.ListCollectionsResponse {
	return o.Payload
}

func (o *ListCollectionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListCollectionsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListCollectionsBadRequest creates a ListCollectionsBadRequest with default headers values
func NewListCollectionsBadRequest() *ListCollectionsBadRequest {
	return &ListCollectionsBadRequest{}
}

/*
ListCollectionsBadRequest describes a response with status code 400, with default header values.

For error reasons, review the response data.
*/
type ListCollectionsBadRequest struct {
}

// IsSuccess returns true when this list collections bad request response has a 2xx status code
func (o *ListCollectionsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list collections bad request response has a 3xx status code
func (o *ListCollectionsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list collections bad request response has a 4xx status code
func (o *ListCollectionsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list collections bad request response has a 5xx status code
func (o *ListCollectionsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list collections bad request response a status code equal to that given
func (o *ListCollectionsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list collections bad request response
func (o *ListCollectionsBadRequest) Code() int {
	return 400
}

func (o *ListCollectionsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/collections][%d] listCollectionsBadRequest ", 400)
}

func (o *ListCollectionsBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v2/collections][%d] listCollectionsBadRequest ", 400)
}

func (o *ListCollectionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListCollectionsInternalServerError creates a ListCollectionsInternalServerError with default headers values
func NewListCollectionsInternalServerError() *ListCollectionsInternalServerError {
	return &ListCollectionsInternalServerError{}
}

/*
ListCollectionsInternalServerError describes a response with status code 500, with default header values.

Internal server error. Please open a support ticket so OpenSea can investigate.
*/
type ListCollectionsInternalServerError struct {
}

// IsSuccess returns true when this list collections internal server error response has a 2xx status code
func (o *ListCollectionsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list collections internal server error response has a 3xx status code
func (o *ListCollectionsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list collections internal server error response has a 4xx status code
func (o *ListCollectionsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list collections internal server error response has a 5xx status code
func (o *ListCollectionsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list collections internal server error response a status code equal to that given
func (o *ListCollectionsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list collections internal server error response
func (o *ListCollectionsInternalServerError) Code() int {
	return 500
}

func (o *ListCollectionsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v2/collections][%d] listCollectionsInternalServerError ", 500)
}

func (o *ListCollectionsInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v2/collections][%d] listCollectionsInternalServerError ", 500)
}

func (o *ListCollectionsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
